extern const GeoLayout terminator_ring_trail_geo[];
extern Lights1 terminator_ring_trail_f3dlite_material_003_lights;
extern Vtx terminator_ring_trail_Torus_mesh_layer_1_vtx_0[1500];
extern Gfx terminator_ring_trail_Torus_mesh_layer_1_tri_0[];
extern Gfx mat_terminator_ring_trail_f3dlite_material_003[];
extern Gfx terminator_ring_trail_Torus_mesh_layer_1[];
extern Gfx terminator_ring_trail_material_revert_render_settings[];
