extern const GeoLayout lava_fog_transparent_geo[];
extern Lights1 lava_fog_transparent_f3dlite_material_lights;
extern Vtx lava_fog_transparent_Cylinder_mesh_layer_5_vtx_0[155];
extern Gfx lava_fog_transparent_Cylinder_mesh_layer_5_tri_0[];
extern Gfx mat_lava_fog_transparent_f3dlite_material[];
extern Gfx lava_fog_transparent_Cylinder_mesh_layer_5[];
extern Gfx lava_fog_transparent_material_revert_render_settings[];
